// Generated by CoffeeScript 1.6.3
(function() {
  var dedelimit, dedelimitSrc, delimited, notDelimited, path, should, _;

  _ = require("underscore");

  should = require("should");

  path = require("path");

  dedelimitSrc = path.join(__dirname, "../index.js");

  dedelimit = require(dedelimitSrc).dedelimit;

  delimited = {
    "ident.name.first": "Nancy",
    "ident.name.last": "Drew",
    "ident.email": "nancyD_fluffybunny16@myspace.com",
    "age": 26,
    "address.street": "184 West Terrace Ave",
    "address.city": "Miami",
    "pets": ["Rex", "Spike", "Klifford the Kow"]
  };

  notDelimited = {
    ident: {
      name: {
        first: "Nancy",
        last: "Drew"
      },
      email: "nancyD_fluffybunny16@myspace.com"
    },
    age: 26,
    address: {
      street: "184 West Terrace Ave",
      city: "Miami"
    },
    pets: ["Rex", "Spike", "Klifford the Kow"]
  };

  describe("dedelimit", function() {
    it("should instantiate a nested object from a delimited string of object properties.", function(done) {
      return dedelimit(delimited, function(err, restored) {
        restored.should.eql(notDelimited);
        return done();
      });
    });
    return it("should convert {'foo.bar':'whatzit'} into { foo: { bar: 'whatzit'} }", function(done) {
      var _inflated;
      _inflated = {
        foo: {
          bar: "whatzit"
        }
      };
      return dedelimit({
        "foo.bar": "whatzit"
      }, function(err, restored) {
        restored.should.eql(_inflated);
        return done();
      });
    });
  });

}).call(this);
